openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /books:
    get:
      tags:
      - book-controller
      operationId: getAllBooks
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDTO'
    post:
      tags:
      - book-controller
      operationId: addBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookDTO'
        required: true
      responses:
        "201":
          description: Created
  /books/{name}/reserve: # Ajout de la nouvelle route pour réserver un livre par nom dans l'URL
    post:
      tags:
        - book-controller
      operationId: reserveBookByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
  /books/use/{name}/reserve: # Ajout de la route pour réserver un livre par nom dans l'URL
    post:
      tags:
        - book-controller
      operationId: reserveBookByNameUseCase
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    BookDTO:
      type: object
      properties:
        name:
          type: string
        author:
          type: string
